# Import necessary libraries


In [ ]:
#pip install xgboost

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
import xgboost as xgb

# Load the dataset

In [8]:
df=pd.read_csv('DataSets/4.Classification-Pollution_dataset-9i & 4or2 o.csv')

In [10]:
df.info() #  Target = Air Quality 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Temperature                    5000 non-null   float64
 1   Humidity                       5000 non-null   float64
 2   PM2.5                          5000 non-null   float64
 3   PM10                           5000 non-null   float64
 4   NO2                            5000 non-null   float64
 5   SO2                            5000 non-null   float64
 6   CO                             5000 non-null   float64
 7   Proximity_to_Industrial_Areas  5000 non-null   float64
 8   Population_Density             5000 non-null   int64  
 9   Air Quality                    5000 non-null   object 
 10  Binaary_Class                  5000 non-null   object 
dtypes: float64(8), int64(1), object(2)
memory usage: 429.8+ KB


In [12]:
df.drop(columns=['Binaary_Class'],axis=1,inplace=True) 

In [14]:
df.head()

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
0         29.8      59.1    5.2  17.9  18.9   9.2  1.72   
1         28.3      75.6    2.3  12.2  30.8   9.7  1.64   
2         23.1      74.7   26.7  33.8  24.4  12.6  1.63   
3         27.1      39.1    6.1   6.3  13.5   5.3  1.15   
4         26.5      70.7    6.9  16.0  21.9   5.6  1.01   

   Proximity_to_Industrial_Areas  Population_Density Air Quality  
0                            6.3                 319    Moderate  
1                            6.0                 611    Moderate  
2                            5.2                 619    Moderate  
3                           11.1                 551        Good  
4                           12.7                 303        Good

### Label Encoding

In [16]:
# Initialize the LabelEncoder
label_encoder = LabelEncoder()

In [18]:
df['Air Quality'] = label_encoder.fit_transform(df['Air Quality'])

In [20]:
df.head()

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
0         29.8      59.1    5.2  17.9  18.9   9.2  1.72   
1         28.3      75.6    2.3  12.2  30.8   9.7  1.64   
2         23.1      74.7   26.7  33.8  24.4  12.6  1.63   
3         27.1      39.1    6.1   6.3  13.5   5.3  1.15   
4         26.5      70.7    6.9  16.0  21.9   5.6  1.01   

   Proximity_to_Industrial_Areas  Population_Density  Air Quality  
0                            6.3                 319            2  
1                            6.0                 611            2  
2                            5.2                 619            2  
3                           11.1                 551            0  
4                           12.7                 303            0

### Split the data into training and testing sets

In [29]:
X=df.drop(columns=['Air Quality'],axis=1)
y=df['Air Quality']

In [31]:
print(X.shape)
print(y.shape)

(5000, 9)
(5000,)


In [33]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [35]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3750, 9)
(1250, 9)
(3750,)
(1250,)


# Define & Evaluate the model

### 1. AdaBoost Classifier

In [54]:
# Initialize AdaBoost Classifier
ada_boost = AdaBoostClassifier(n_estimators=50, random_state=42)

# Train the model
ada_boost.fit(X_train, y_train)

# Make predictions
y_pred_ada = ada_boost.predict(X_test)

print('-'*55)

# Evaluate the model
accuracy_ada = accuracy_score(y_test, y_pred_ada)
print(f"AdaBoost Classifier Accuracy: {accuracy_ada:.4f}")

print('-'*55)

print("AdaBoost Classifier Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_ada))

print('-'*55)

print("AdaBoost Classifier Classification Report:")
print(classification_report(y_test, y_pred_ada))

print('-'*55)

-------------------------------------------------------
AdaBoost Classifier Accuracy: 0.7368
-------------------------------------------------------
AdaBoost Classifier Confusion Matrix:
[[359   0 149   0]
 [  0  47   3  82]
 [  3   0 346  32]
 [  0   1  59 169]]
-------------------------------------------------------
AdaBoost Classifier Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.71      0.83       508
           1       0.98      0.36      0.52       132
           2       0.62      0.91      0.74       381
           3       0.60      0.74      0.66       229

    accuracy                           0.74      1250
   macro avg       0.80      0.68      0.69      1250
weighted avg       0.81      0.74      0.74      1250

-------------------------------------------------------


### 2. Gradient Boosting Classifier

In [56]:
# Initialize Gradient Boosting Classifier
grad_boost = GradientBoostingClassifier(n_estimators=50, random_state=42)

# Train the model
grad_boost.fit(X_train, y_train)

# Make predictions
y_pred_grad = grad_boost.predict(X_test)

print('-'*55)

# Evaluate the model
accuracy_grad = accuracy_score(y_test, y_pred_grad)
print(f"Gradient Boosting Classifier Accuracy: {accuracy_grad:.4f}")

print('-'*55)

print("Gradient Boosting Classifier Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_grad))

print('-'*55)

print("Gradient Boosting Classifier Classification Report:")
print(classification_report(y_test, y_pred_grad))

print('-'*55)

-------------------------------------------------------
Gradient Boosting Classifier Accuracy: 0.9488
-------------------------------------------------------
Gradient Boosting Classifier Confusion Matrix:
[[508   0   0   0]
 [  0 110   0  22]
 [  4   0 364  13]
 [  0  12  13 204]]
-------------------------------------------------------
Gradient Boosting Classifier Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       508
           1       0.90      0.83      0.87       132
           2       0.97      0.96      0.96       381
           3       0.85      0.89      0.87       229

    accuracy                           0.95      1250
   macro avg       0.93      0.92      0.92      1250
weighted avg       0.95      0.95      0.95      1250

-------------------------------------------------------


### 3. XGBoost Classifier

In [57]:
# Initialize XGBoost Classifier
xgb_model = xgb.XGBClassifier(n_estimators=50, random_state=42)

# Train the model
xgb_model.fit(X_train, y_train)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)

print('-'*55)

# Evaluate the model
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Classifier Accuracy: {accuracy_xgb:.4f}")

print('-'*55)

print("XGBoost Classifier Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

print('-'*55)

print("XGBoost Classifier Classification Report:")
print(classification_report(y_test, y_pred_xgb))

print('-'*55)

-------------------------------------------------------
XGBoost Classifier Accuracy: 0.9568
-------------------------------------------------------
XGBoost Classifier Confusion Matrix:
[[508   0   0   0]
 [  0 115   1  16]
 [  0   0 366  15]
 [  0  13   9 207]]
-------------------------------------------------------
XGBoost Classifier Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       508
           1       0.90      0.87      0.88       132
           2       0.97      0.96      0.97       381
           3       0.87      0.90      0.89       229

    accuracy                           0.96      1250
   macro avg       0.94      0.93      0.93      1250
weighted avg       0.96      0.96      0.96      1250

-------------------------------------------------------
